import Head from "next/head";
import Link from "next/link";
import Navbar from "../Components/Navbar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <Navbar />
 
      <div className={styles.main}>
        <h1 className="text-6xl font-extrabold">All About SpaceX</h1>
        <div className="flex justify-evenly w-1/2 mt-2">
          <div className="flex-col">
            <h1 className="text-xl">About</h1>
            <p className="text-sm">Founded by Elon Musk in 2002</p>
            <p className="text-sm">Has 9500 Employees,</p>
            <p className="text-sm">4 vehicles,</p>
            <p className="text-sm">3 launch sites,</p>
            <p className="text-sm">3 test sites,</p>
          </div>
          <div>
            <h1 className="text-xl">Headquarters</h1>
            <p className="text-sm">Rocket Road,</p>
            <p className="text-sm">Hawthrone,California</p>
          </div>
          <div>
            <h1 className="text-xl">Social Media</h1>
            <p className="text-sm">
              <Link href="https://www.spacex.com/">Website</Link>
            </p>
            <p className="text-sm">
              <Link href="/">Flickr</Link>
            </p>
            <p className="text-sm">
              <Link href="/">Twitter</Link>
            </p>
            <p className="text-sm">
              <Link href="/">Elon Musk Twitter</Link>
            </p>
          </div>
        </div>
        <h1 className="text-xl">Mission</h1>
        <p className="text-center text-base">“You want to wake up in the morning and think the future is going to be great - and that’s what being a spacefaring civilization is all about. <br /> It’s about believing in the future and thinking that the future will be better than the past. <br /> And I can’t think of anything more exciting than going out there and being among the stars.” <br />
-Elon Musk</p>
      </div>
    </div>
  );
}
